version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres_container
    ports:
      - "7777:5432" # host:container
    volumes:
      - ./pgdata:/var/lib/postgresql/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # restart: always


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    container_name: web-django-app
    restart: always
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    # command: bash -c "python manage.py runserver 0.0.0.0:8000"
    # python manage.py makemigrations && python manage.py migrate && 

  # volumes:
  #   data: